apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  tolerations:
  - key: "app"
    operator: "Equal" 
    value: "blue"
    effect: NoSchedule

# kubectl taint nodes kubeworker1 app=blue:NoSchedule