apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: data-processor
    image: data-processor
    resources:
      limits:
        memory: 100Mi
        cpu: 500m
  nodeSelector:
    size: Large
  
# kubectl label nodes <node-name> size=Large