apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pd
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: myapp
          image: nginx
          ports:
            - containerPort: 80
  replicas: 6
  selector:
    matchLabels:
      type: front-end
